# Generated by Django 5.0.3 on 2024-03-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('Product_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_price', models.IntegerField()),
                ('Product_brand', models.CharField(max_length=100)),
                ('Product_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
